import type { Agent, AgentDetailData } from "@/components/marketplace/agentData";

export const agentsES: Agent[] = [
  {
    id: 1,
    category: "LEGAL",
    agentName: "Revisión de Riesgo Legal en T&C",
    initials: "JM",
    professional: "John Morales R. · Abogado Comercial, 13 años",
    description: "Análisis de términos y condiciones para sitios web comerciales. Detecta exposición regulatoria a partir del lenguaje del sitio.",
    calibration: "50h+",
    status: "En calibración",
    isComingSoon: false,
  },
  {
    id: 2,
    category: "PSICOLOGÍA",
    agentName: "Evaluación de Dinámica Familiar",
    initials: "PT",
    professional: "Profesional Piloto · Psicóloga Infantil, 15 años",
    description: "Evalúa problemas conductuales infantiles a través de la dinámica familiar y el entorno adulto.",
    calibration: "50h+",
    status: "En calibración",
    isComingSoon: false,
  },
  {
    id: 3,
    category: "COACHING",
    agentName: "Estrategia de Transición de Carrera",
    initials: "CE",
    professional: "Profesional Piloto · Coach de Empleabilidad",
    description: "Planes personalizados de transición de carrera basados en posicionamiento de mercado y análisis de perfil profesional.",
    calibration: "50h+",
    status: "En calibración",
    isComingSoon: false,
  },
  {
    id: 4,
    category: "FINANZAS",
    agentName: "Modelo de Valoración de Startups",
    initials: "AR",
    professional: "Próximamente · Banca de Inversión",
    description: "Valoración de empresas en etapa temprana usando transacciones comparables y análisis DCF.",
    calibration: "Pendiente",
    status: "--",
    isComingSoon: true,
  },
  {
    id: 5,
    category: "CONTABILIDAD",
    agentName: "Revisión de Optimización Fiscal",
    initials: "ML",
    professional: "Próximamente · Contador Tributario",
    description: "Identifica oportunidades de optimización fiscal para pequeñas empresas según regulaciones vigentes.",
    calibration: "Pendiente",
    status: "--",
    isComingSoon: true,
  },
  {
    id: 6,
    category: "CONSULTORÍA",
    agentName: "Brief de Consultoría Estratégica",
    initials: "DS",
    professional: "Próximamente · Consultor de Estrategia",
    description: "Análisis estructurado de problemas de negocio usando frameworks calibrados con 20 años de consultoría.",
    calibration: "Pendiente",
    status: "--",
    isComingSoon: true,
  },
];

export const agentDetailsES: Record<number, AgentDetailData> = {
  1: {
    initials: "JM",
    name: "John Morales R.",
    credential: "Abogado Comercial · 13 años de práctica",
    location: "Bogotá, Colombia",
    agentName: "Revisión de Riesgo Legal en T&C",
    description: "Este agente analiza términos y condiciones para sitios web comerciales, detectando exposición regulatoria del lenguaje del sitio, riesgos jurisdiccionales y brechas de cumplimiento que la revisión legal estándar pasaría por alto. Construido a partir de 13 años de práctica en derecho comercial.",
    steps: [
      "Recopila registro de empresa, URL del sitio web, T&C actuales, descripción del negocio y referencias de competidores.",
      "Analiza el lenguaje del sitio web, mapea enfoques regulatorios de competidores y cruza todo contra los T&C.",
      "Produce una evaluación de riesgo identificando exposición regulatoria y entrega T&C revisados con monitoreo continuo.",
    ],
    metrics: [
      { value: "50h+", label: "Calibración" },
      { value: "13", label: "Años de Experiencia" },
      { value: "1hr", label: "Entrega Promedio" },
    ],
    formHeader: "Iniciar una Consulta",
    formFields: [
      { name: "businessName", label: "Nombre de la empresa", type: "text", placeholder: "Nombre de tu empresa", required: true },
      { name: "websiteUrl", label: "URL del sitio web", type: "text", placeholder: "https://tusitio.com", required: true },
      { name: "email", label: "Correo electrónico", type: "text", placeholder: "tu@empresa.com", required: true },
      { name: "businessDescription", label: "Describe tu negocio", type: "textarea", placeholder: "Breve descripción de lo que haces" },
    ],
    pricing: [
      { label: "Revisión única", price: "$200" },
      { label: "Monitoreo mensual", price: "$20/mes" },
    ],
    ctaText: "Solicitar Revisión",
  },
  2: {
    initials: "PT",
    name: "Profesional Piloto",
    credential: "Psicóloga Infantil · 15 años de práctica",
    location: "Por anunciar",
    agentName: "Evaluación de Dinámica Familiar",
    description: "Este agente evalúa problemas conductuales infantiles analizando el entorno familiar, la dinámica entre adultos y los factores contextuales que la experiencia clínica ha demostrado son los verdaderos motores del comportamiento infantil. Construido a partir de 15 años de práctica y más de 8,000 evaluaciones digitalizadas.",
    steps: [
      "Recopila información sobre la edad del niño, comportamientos presentados y composición familiar.",
      "Indaga el entorno adulto: dinámica entre padres, patrones de conflicto, rutinas y respuestas emocionales al comportamiento del niño.",
      "Produce una evaluación preliminar identificando contribuyentes ambientales probables y recomienda próximos pasos, incluyendo si se necesita evaluación presencial.",
    ],
    metrics: [
      { value: "50h+", label: "Calibración" },
      { value: "8,000", label: "Base de Evaluaciones" },
      { value: "45min", label: "Entrega Promedio" },
    ],
    formHeader: "Solicitar una Evaluación",
    formFields: [
      { name: "childAge", label: "Edad del niño", type: "text", placeholder: "Ej. 4 años", required: true },
      { name: "concern", label: "Breve descripción de la preocupación", type: "textarea", placeholder: "Describe los problemas conductuales o preocupaciones", required: true },
      { name: "email", label: "Correo electrónico", type: "text", placeholder: "tu@email.com", required: true },
      { name: "language", label: "Idioma preferido", type: "text", placeholder: "Español / Inglés" },
    ],
    pricing: [
      { label: "Evaluación inicial", price: "$150" },
      { label: "Sesión de seguimiento", price: "$75" },
    ],
    ctaText: "Solicitar Evaluación",
  },
  3: {
    initials: "CE",
    name: "Profesional Piloto",
    credential: "Coach de Empleabilidad · Ex Head de Waze Latam",
    location: "Por anunciar",
    agentName: "Estrategia de Transición de Carrera",
    description: "Este agente diseña estrategias personalizadas de transición de carrera analizando perfiles profesionales, posicionamiento de mercado, habilidades transferibles y demanda industrial. Construido a partir de años de coaching ejecutivo y colocación de talento a escala.",
    steps: [
      "Analiza tu perfil profesional actual: experiencia, habilidades, logros y brechas de posicionamiento.",
      "Mapea tu perfil contra la demanda del mercado, identifica rutas de transición de alto valor y señala habilidades a desarrollar.",
      "Entrega una estrategia de transición con acciones específicas, cronograma y recomendaciones de posicionamiento para tus roles o industrias objetivo.",
    ],
    metrics: [
      { value: "50h+", label: "Calibración" },
      { value: "500+", label: "Perfiles Analizados" },
      { value: "1hr", label: "Entrega Promedio" },
    ],
    formHeader: "Inicia Tu Estrategia",
    formFields: [
      { name: "currentRole", label: "Rol actual y empresa", type: "text", placeholder: "Ej. Product Manager en Startup", required: true },
      { name: "targetRole", label: "Rol o industria objetivo", type: "text", placeholder: "Ej. VP Producto en Serie B+", required: true },
      { name: "email", label: "Correo electrónico", type: "text", placeholder: "tu@email.com", required: true },
      { name: "linkedIn", label: "URL de LinkedIn", type: "text", placeholder: "https://linkedin.com/in/" },
    ],
    pricing: [
      { label: "Estrategia completa", price: "$180" },
      { label: "Estrategia + seguimiento 30 días", price: "$35/mes" },
    ],
    ctaText: "Solicitar Estrategia",
  },
};
